version: "3.0"
services:
  kong-database:
    image: postgres:9.6 ##cant used alpine 
    restart: always
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kong_db
    ports:
      - 5432:5432
    networks:
      - kong-net
      
  kong-migrate:
    image: kong:alpine #or use kong:latest
    restart: on-failure
    command: kong migrations up # if use latest kong change with "kong migration up"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=password
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:alpine #or use kong:latest
    restart: always
    environment:
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=ngantri
      - KONG_PG_PASSWORD=ngantri2021
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - kong-migrate
      - kong-database
    networks:
      - kong-net

  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://user:password@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  konga:
    image: pantsel/konga:next
    restart: on-failure
    networks:
      - kong-net
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=user
      - DB_PASSWORD=password
      - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjd #you cant change this with whatever you want
      - DB_DATABASE=konga_db
      - NODE_ENV=production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

  project:
    build: ./project
    restart: always
    networks: 
      - kong-net
    ports:
      - "3000:3000"

networks:
  kong-net:
    driver: bridge
